In [1]:
import numpy as np

In [2]:
vectorAsList = [1, 2, 3, 4, 5]
vectorAsNumpyArray = np.array([1, 2, 3, 4, 5])
rowVectorAsNumpyArray = np.array([[1, 2, 3, 4, 5], [2, 3, 4, 5, 6]])
columnVectorAsNumpyArray = np.array([[1], [2], [3], [4], [5]])

In [5]:
print("vectorAsList:", vectorAsList)
print("vectorAsNumpyArray:", vectorAsNumpyArray) 
print("rowVectorAsNumpyArray:", rowVectorAsNumpyArray)
print("columnVectorAsNumpyArray:", columnVectorAsNumpyArray)

vectorAsList: [1, 2, 3, 4, 5]
vectorAsNumpyArray: [1 2 3 4 5]
rowVectorAsNumpyArray: [[1 2 3 4 5]
 [2 3 4 5 6]]
columnVectorAsNumpyArray: [[1]
 [2]
 [3]
 [4]
 [5]]


In [6]:
### vector addition:

vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])
vector_sum = vector1 + vector2

In [7]:
print(vector_sum)  # Output: [5 7 9]

[5 7 9]


In [9]:
### vector subtraction:
vector_diff = vector2 - vector1 
print(vector_diff)  # Output: [-3 -3 -3]

[3 3 3]


### The Dot Product

In [10]:
np.dot(vector1, vector2)  # Output: 32

np.int64(32)